export const APP_NAME = 'Ortaq Maliyyə';
export const ROUTES = {
    login: '/login',
    dashboard: '/',
    transactions: '/transactions',
    fixedExpenses: '/fixed-expenses',
    transactionNew: '/transactions/new',
    transactionNewIncome: '/transactions/new/income',
    transactionNewExpense: '/transactions/new/expense',
    transactionNewTransfer: '/transactions/new/transfer',
    stats: '/stats',
    notifications: '/notifications',
    profile: '/profile',
    admin: '/admin',
};
export const API_ROUTES = {
    me: '/auth/me',
    login: '/auth/login',
    logout: '/auth/logout',
    dashboardSummary: '/dashboard/summary',
    dashboardRecent: '/dashboard/recent',
    transactions: '/transactions',
    transfers: '/transfers',
    transferUsers: '/transfer-users',
    fixedExpenses: '/fixed-expenses',
    categories: '/categories',
    statsOverview: '/stats/overview',
    statsByCategory: '/stats/by-category',
    statsByUser: '/stats/by-user',
    notificationPreferences: '/notification-preferences',
    pushSubscribe: '/push/subscribe',
    syncBatch: '/sync/batch',
    adminSummary: '/admin/summary',
    adminUsers: '/admin/users',
    adminAuditLogs: '/admin/audit-logs',
};
